### PR TITLE
Make opt_skipImports a project setting

### PR DESCRIPTION
**Pull request by jyhsu**
Hello @nicks, @dpup,

Please review the following commits I made in branch 'jean-skipImports'.

5e2e1b3aaeadd773a7bd0acfbd7bf2de589da98d (2015-06-17 14:20:12 -0700)
Make opt_skipImports a project setting

R=@nicks
R=@dpup

### CODE REVIEW

**Comment by nicks** [comment]
maybe it should be a setter instead of a ctor arg?

otherwise lgtm!

**Comment by dpup** [comment]
This makes the API not backward compatible. Suggest leaving both options in or incrementing the mibir version.

**Comment by jyhsu** [comment]
Oops I removed the option on addJob (probably should have kept it there). I
did increment the version to 0.2.2 though, is that what you mean?

**Comment by dpup** [comment]
For API incompatible change it should go to `0.3.0`

**Pull request merged**
