### PR TITLE
compile does not generate files for imported protos

### PR DESCRIPTION
**Pull request by jyhsu**
Hello @nicks,

Please review the following commits I made in branch 'jean-version'.

1761a3933a582c49d45a2b9fb1733a13f3d80ddd (2015-07-07 14:27:48 -0700)
compile does not generate files for imported protos

R=@nicks

### CODE REVIEW

**Comment by nicks** [comment]
should we just get rid of skipImports? now that i think more about it, i don't think the option makes sense. "only output direct inputs but process all imports" seems like the right behavior in all cases.

**Comment by jyhsu** [comment]
yah maybe, bc we added it bc it wasn't working, but now you fixed it, right? that would make things a lot easier.

**Comment by jyhsu** [comment]
ok i will do that and see how it goes. hold tight!

**Comment by jyhsu** [comment]
@nicks ok this is ready for a look!

**Comment by jyhsu** [comment]
when linked to medium2 on my dev machine, i had to add descriptor.proto (so that it would generate the .js files in the out dir, but other than that, the imports work fine)

**Comment by nicks** [comment]
lg

**Pull request merged**
